// Day plans for option B, "Seoul · Seoraksan · Gangneung". Coordinates come from the catalog where a catalog id is given.
import { item, meal } from "./lib.mjs";

const HOTEL = { lat: 37.5745, lon: 126.9925 }; // 4rest Stay Jongno
const SORANO = { lat: 38.1965, lon: 128.539 };
const SEONGYOJANG = { lat: 37.7867, lon: 128.8851 };

export default [
  {
    date: "2026-10-17", dow: "Sat", base: "Seoul",
    title: "Dawn landing, the royal shrine, a lantern-lit palace pond",
    summary: "Taxi straight to a room that is already yours (booked from Oct 16) and sleep until lunch. Then stay within ten minutes of the hotel: Jongmyo on its one free-roaming day of the week, Gwangjang Market for dinner, and the Mulbit Yeonhwa light show on Changgyeonggung's pond.",
    autumn_note: "Jongmyo's old zelkovas and Changgyeonggung's Chundangji pond are starting to color. The Seoul Eulalia Festival opens today, but this plan saves it for its last evening (Fri 23). Sunset about 17:55.",
    items: [
      item("05:15", "06:30", "transport", "Land at Incheon T1, immigration and bags", "incheon-airport-t1", "With the e-Arrival Card filed in advance, immigration is quick at this hour. Buy a T-money card at a convenience store in arrivals and load ₩30,000 cash each; switch on your eSIM.", { lat: 37.4492, lon: 126.4508 }),
      item("06:30", "07:40", "transport", "Taxi to 4rest Stay Jongno", null, "Regular taxi from the arrivals rank or Kakao T, about ₩65,000-80,000 for the car with tolls. Show the driver the hotel's Korean address.", { cost_krw_pp: 25000, cost_note: "car fare split 3 ways", ...HOTEL }),
      item("07:40", "11:45", "rest", "Check in and sleep", "4rest-stay-jongno", "The room is booked from the night of Oct 16, so it is ready when you land. Sleep 3-4 hours, shower, and get outside by noon: daylight is the fastest jet-lag fix."),
      item("12:00", "13:15", "food", "Lunch in the Ikseon-dong hanok alleys", "ikseon-dong", "A tight grid of 1920s hanok turned into cafés and small restaurants, 3 minutes from the hotel."),
      item("13:30", "15:15", "sight", "Jongmyo, the royal ancestral shrine", "jongmyo", "Jongmyo's main hall (101 m of red columns on a stone platform) is one of the most moving buildings in Korea. Weekdays are guided tours only; on Saturdays you can wander at your own pace.", { cost_krw_pp: 1000, tip: "The raised center of the stone paths is the 'spirit road'; walk on either side." }),
      item("15:30", "17:30", "rest", "Hotel break", null, "Nap or shower before the evening. Jet lag hits hardest around 16:00 on day one.", { ...HOTEL }),
      item("17:30", "18:50", "food", "Gwangjang Market food alley", "gwangjang-market", "Seoul's oldest covered market: sit at a stall counter for mung-bean pancakes fried in front of you, beef tartare and 'addictive' mini gimbap."),
      item("19:00", "20:30", "night", "Changgyeonggung Mulbit Yeonhwa night show", "changgyeonggung", "The palace stays open to 21:00. Walk the lit grounds to Chundangji pond for the 16-minute media-art show projected over the water (19:00, 19:30 or 20:00), and the white Victorian greenhouse.", { cost_krw_pp: 1000, cost_note: "show ticket includes palace entry", booking: "Ticketlink or Creatrip, up to 4 per person; walk-up palace entry if the show is sold out" }),
      item("20:45", "22:00", "night", "Jongno 3-ga tent bars (optional)", "jongno3ga-pojangmacha", "Orange tents along the street with soju and grilled skewers, a 5-minute walk from the hotel."),
    ],
    food: [
      meal("lunch", "Changhwadang (Ikseon-dong)", "창화당 익선동", null, 12000, "Crisp tteokgalbi dumplings and spicy rice cakes in a hanok; expect a short queue.", { lat: 37.5741, lon: 126.9901 }),
      meal("dinner", "Gwangjang Market crawl: Soonhee-ne bindaetteok + Buchon Yukhoe", "광장시장 순희네빈대떡 · 부촌육회", "gwangjang-crawl", 25000, "Share a bindaetteok, a plate of yukhoe and a roll of mayak gimbap."),
      meal("drinks", "Jongno 3-ga pojangmacha", "종로3가 포장마차", "jongno-tents", 20000, "Soju, eomuk soup and skewers; most tents take cards."),
    ],
    rainy_swap: "Jongmyo's halls have deep eaves, but in heavy rain swap it for the National Museum of Korea (free, open to 21:00 on Saturdays). Gwangjang Market is covered. Mulbit Yeonhwa may be cancelled in rain; the lit palace is still open.",
    stay_stop: "seoul-1",
  },
  {
    date: "2026-10-18", dow: "Sun", base: "Seoul",
    title: "The Secret Garden, hanok rooftops, a car-free bridge at dusk",
    summary: "The royal Secret Garden tour in the morning, Bukchon's lanes and Samcheong-dong in the afternoon, then south to the Han River for the car-free Jamsu Bridge festival and the Banpo rainbow fountain.",
    autumn_note: "Huwon's maples are just starting (peak late Oct to early Nov). The car-free Jamsu Bridge festival runs today, about 12:00-21:00. Sunset about 17:54.",
    items: [
      item("09:30", "12:15", "sight", "Changdeokgung + Huwon (Secret Garden) tour", "changdeokgung-huwon", "The most graceful of the five palaces, built to follow the hills. The 90-minute Huwon tour winds past ponds and pavilions the kings used for study, poetry and boating.", { cost_krw_pp: 8000, booking: "Huwon tickets open Mon Oct 12 at 10:00 KST (Sun Oct 11, 21:00 New York time) on the official site; aim for a 10:00-11:00 slot. A few on-site tickets go on sale at 09:00." }),
      item("12:30", "13:30", "food", "Lunch in Samcheong-dong", null, "A 10-minute walk west from the palace into the lanes below the Blue House hills.", { lat: 37.5856, lon: 126.9822 }),
      item("13:30", "15:30", "walk", "Bukchon hanok lanes", "bukchon", "Climb Bukchon-ro 11-gil for the view over tiled roofs toward downtown, then wander down through Gahoe-dong. It is a lived-in neighborhood: keep voices down.", { tip: "Tourists are allowed in the red-zone lanes only 10:00-17:00 (fines up to ₩100,000)." }),
      item("15:30", "16:45", "rest", "Hotel break", null, "Rest your legs before the evening by the river.", { ...HOTEL }),
      item("17:00", "19:15", "walk", "Jamsu Bridge car-free festival", "han-river-parks", "Line 3 from Jongno 3-ga to Express Bus Terminal (20 min), then 10 minutes on foot to Banpo Hangang Park. The low-level Jamsu Bridge is closed to cars on these Sundays, with food trucks and buskers over the water as the sun sets.", { lat: 37.5106, lon: 126.9958 }),
      item("19:30", "20:30", "night", "Banpo Moonlight Rainbow Fountain", null, "Sit on the riverbank steps for the 20-minute show (19:30, 20:00, 20:30, 21:00): 10,000 nozzles along the Banpo Bridge deck, lit in color.", { lat: 37.5113, lon: 126.996 }),
    ],
    food: [
      meal("lunch", "Samcheong-dong Sujebi", "삼청동수제비", null, 11000, "Hand-torn dough soup and potato pancakes in an old house; a Samcheong-dong institution.", { lat: 37.5856, lon: 126.9822 }),
      meal("dinner", "Chimaek picnic on the Han River", "한강 치맥", "chimaek-hangang", 12000, "Fried chicken and beer on the riverbank is a Seoul ritual. Buy from the park's convenience stores or the festival food trucks.", { lat: 37.5106, lon: 126.9958 }),
    ],
    rainy_swap: "Huwon tours run in light rain. If it pours, swap the river evening for the Starfield COEX Library and Bongeunsa temple across the street, or a long soak at SPAREX Dongdaemun (24 h jjimjilbang).",
    stay_stop: "seoul-1",
  },
  {
    date: "2026-10-19", dow: "Mon", base: "Sokcho / Seoraksan",
    title: "Over the mountains to the sea: a refugee village and a hot-spring night",
    summary: "A Monday-morning bus across the Taebaek range (weekends can take twice as long), lunch in Abai Village, the hand-pulled raft across the harbor to Sokcho's market, then the Seorak gate and an evening in Waterpia's outdoor hot-spring pools. Travel with day packs; the suitcases wait in Seoul.",
    autumn_note: "The bus crosses the mountains through Inje: your first look at peak color from the window. Red snow crab and Yangyang pine mushrooms are in season. Sunset about 17:40.",
    items: [
      item("07:30", "07:55", "transport", "Taxi to Dong Seoul Bus Terminal", null, "Leave the big bags at 4rest Stay (confirm in advance). Or subway: Line 5 to Dongdaemun History & Culture Park, then Line 2 to Gangbyeon, about 35 min.", { cost_krw_pp: 5000, cost_note: "car fare split 3 ways; counted in local transit", lat: 37.5349, lon: 127.0947 }),
      item("08:20", "10:36", "transport", "Deluxe bus, Dong Seoul → Sokcho", null, "Express bus to Sokcho Express Bus Terminal by Cheongchoho lake, about 2 h 15 min on a weekday. Sit on the right for the mountain views after Inje.", { cost_krw_pp: 22800, booking: "kobus.co.kr or the T-money Bus app; foreign Visa/Mastercard accepted", lat: 38.1918, lon: 128.5995 }),
      item("10:45", "12:45", "walk", "Abai Village and the gaetbae raft", "abai-village-gaetbae", "Settled by refugees from North Korea's Hamgyeong province after 1950, the sandbar village still cooks their dishes: squid stuffed with rice (ojingeo sundae) and Hamheung-style cold noodles. After lunch, cross the harbor channel on the gaetbae, a flat raft you pull yourselves along a cable.", { cost_krw_pp: 1000, cost_note: "₩500 each way, cash" }),
      item("12:45", "14:15", "shop", "Sokcho Jungang Market", "sokcho-jungang-market", "Pick up a box of Manseok dakgangjeong (crisp sweet-spicy fried chicken, the town's famous snack) for tonight, and look at the basement fish floor. Coffee at Chilseong Shipyard, a café in a 1952 wooden-boat yard on the lake.", { tip: "Mon Oct 19 is the 3rd Monday, when some stalls close; Manseok is usually open." }),
      item("14:20", "14:40", "transport", "Taxi to Hanwha Resort Seorak Sorano", "hanwha-resort-seorak-sorano", "About ₩15,000 for the car to the resort at the Seorak entrance.", { cost_krw_pp: 5000, cost_note: "counted in local transit" }),
      item("14:45", "17:45", "rest", "Check in, slow afternoon", null, "The condo has a kitchen and a balcony toward the ridge. Rest after the early start.", { ...SORANO }),
      item("18:00", "20:30", "spa", "Seorak Waterpia night spa", "seorak-waterpia", "Outdoor hot-spring pools under the Seorak ridge. Swimsuits on: it is a spa park, not a nude bath. Night spa 18:00-20:30, last entry 20:00.", { cost_krw_pp: 27000, cost_note: "included in the sweet-tier ALL INCLUSIVE rate" }),
      item("20:45", "21:45", "food", "Dakgangjeong and beer in the condo", null, "Eat the market chicken with convenience-store beer on the balcony.", { ...SORANO }),
    ],
    food: [
      meal("lunch", "Dancheon Sikdang (Abai Village)", "단천식당", "dancheon-sikdang", 15000, "Ojingeo sundae and Abai sundae, the refugee village's own recipes."),
      meal("snack", "Chilseong Shipyard café", "칠성조선소", "chilsung-shipyard-cafe", 8000, "Coffee in an old boat-building shed on Cheongchoho lake."),
      meal("dinner", "Manseok Dakgangjeong", "만석닭강정", "manseok-dakgangjeong", 8000, "A medium box feeds three as part of dinner; ask for half spicy."),
    ],
    rainy_swap: "The bus and Abai Village work in drizzle (the raft runs in rain). In a downpour skip the market wander and go straight to Waterpia: hot outdoor pools in the rain are still good.",
    stay_stop: "sokcho",
  },
  {
    date: "2026-10-20", dow: "Tue", base: "Sokcho / Seoraksan",
    title: "Seoraksan at peak: first cable car up, then the granite valley",
    summary: "The trip's big nature day, on a weekday: the first cable car up to Gwongeumseong for the ridge view, the near-flat valley walk to Biseondae's granite walls, Sinheungsa's great bronze Buddha, an outdoor hot-spring soak at Cheoksan, and red snow crab by the harbor.",
    autumn_note: "Seoraksan's valleys are forecast at peak Oct 20-27 (Korea Forest Service whole-mountain peak: Oct 20); the high ridges may be just past peak. Gwongeumseong is 5-10°C colder than the coast.",
    items: [
      item("07:30", "07:45", "transport", "Taxi to Sogongwon (park entrance)", "seoraksan-sogongwon-sinheungsa", "Ask the front desk to book it the night before. Weekday foliage traffic controls still let taxis through early.", { cost_krw_pp: 3500, cost_note: "counted in local transit" }),
      item("07:50", "10:00", "sight", "Seorak cable car to Gwongeumseong", "seorak-cable-car", "Tickets are sold same-day only and printed with a boarding time, so be at the office as it opens (about 08:00-08:30; check sorakcablecar.co.kr). The car climbs 700 m in 5 minutes; walk 10 minutes to the bare-rock fortress summit with Ulsanbawi and the Dinosaur Ridge around you.", { cost_krw_pp: 16000, tip: "If your boarding time is hours away, walk to Biseondae first and ride on the way back." }),
      item("10:15", "13:15", "walk", "Sogongwon → Biseondae valley walk", "biseondae-geumganggul", "A near-flat 3 km riverside path to Biseondae, a gorge of sheer granite walls under the maples. Strong walkers can add the steep stairs to Geumganggul cave (about 1 h return) for the view down the valley."),
      item("13:15", "14:00", "food", "Lunch at the Sogongwon restaurant row", null, "Mountain-vegetable bibimbap and potato pancakes by the park entrance.", { lat: 38.1735, lon: 128.4905 }),
      item("14:00", "14:40", "sight", "Sinheungsa and the bronze Buddha", "seoraksan-sogongwon-sinheungsa", "A temple founded in 652 at the trailhead, with a 14.6 m bronze 'Unification Buddha' facing the valley."),
      item("15:00", "17:00", "spa", "Cheoksan Hot Spring", "cheoksan-hot-spring", "A 53°C alkaline spring piped to single-sex baths with an outdoor pool in the pines: the most onsen-like soak in Gangwon. Nude, as in Japan; towels provided. Hot after a hiking day.", { cost_krw_pp: 11000 }),
      item("17:30", "19:15", "food", "Red snow crab at Dongmyeong Port", null, "Pick red snow crab (hongge) from the tanks; they steam it and finish with fried rice in the shell.", { lat: 38.2125, lon: 128.5985 }),
      item("19:15", "19:45", "walk", "Yeonggeumjeong rock pavilion", "yeonggeumjeong-lighthouse", "A footbridge pavilion over the surf rocks next to the crab restaurants, lit at night. Taxi back to Sorano after."),
    ],
    food: [
      meal("lunch", "Seorak-dong sanchae bibimbap", "설악동 산채비빔밥", null, 15000, "Mountain greens over rice with doenjang soup, plus a pajeon to share.", { lat: 38.1735, lon: 128.4905 }),
      meal("dinner", "Red snow crab, Dongmyeong Port", "동명항 홍게", "dongmyeong-red-crab", 40000, "Autumn crab season; agree the price by weight before they cook it."),
    ],
    rainy_swap: "Wind stops the cable car and cloud hides the ridges. If Tuesday is a washout, swap days: do Naksansa and the coast today and Seorak on Wednesday morning, then take the intercity bus Sokcho → Gangneung (₩8,400, about 1 h) in the afternoon.",
    stay_stop: "sokcho",
  },
  {
    date: "2026-10-21", dow: "Wed", base: "Gangneung",
    title: "Down the coast: a sea-cliff temple, a pine-topped lighthouse, the coffee town",
    summary: "Four short taxi hops down the coast: Naksansa's seaside pavilions, Hajodae's pine-crowned rock, a fish-market lunch at Jumunjin, then Gangneung, a night in a 300-year-old manor and the Coffee Festival's opening evening on Anmok beach.",
    autumn_note: "The Gangneung Coffee Festival opens today (Oct 21-25, 10:00-21:00); weekday evenings are calm. Yangyang pine mushrooms are in their last weeks. Sunset about 17:40.",
    items: [
      item("09:00", "09:30", "transport", "Check out, taxi to Naksansa", null, "About ₩25,000 for the car; no direct bus from the Seorak side.", { cost_krw_pp: 8400, lat: 38.1246, lon: 128.6281 }),
      item("09:30", "11:30", "sight", "Naksansa: Uisangdae and Hongnyeonam", "naksansa", "A temple founded in 671 on a headland. Walk out to Uisangdae, a six-sided pavilion on a pine cliff over the sea, and down to Hongnyeonam, a hermitage built over a sea cave where a hole in the floor shows the waves below. Much was rebuilt after a 2005 wildfire; the setting is the point.", { tip: "The temple has long served free noodles to visitors around lunchtime; ask at the entrance (not confirmed for 2026)." }),
      item("11:40", "12:00", "transport", "Taxi to Hajodae", null, "Call a Kakao T taxi from the Naksansa parking lot.", { cost_krw_pp: 6000, lat: 38.0255, lon: 128.7316 }),
      item("12:00", "12:45", "walk", "Hajodae pavilion and lighthouse", "hajodae", "A pavilion and white lighthouse on a granite headland crowned by a lone pine: the most painted view on this coast."),
      item("12:50", "13:15", "transport", "Taxi to Jumunjin Port", null, "Hajodae has few cruising taxis; book one before you walk out to the point.", { cost_krw_pp: 8400, lat: 37.8936, lon: 128.8301 }),
      item("13:15", "14:30", "food", "Jumunjin Port fish market lunch", "jumunjin-bts-bus-stop", "Gangwon's busiest fishing port: grilled fish set meals and mulhoe (spicy cold raw-fish soup) at the market restaurants."),
      item("14:30", "15:00", "transport", "Taxi to Seongyojang, Gangneung", null, "About ₩27,000 for the car. Cheaper and slower: city bus 300 to downtown, then a short taxi.", { cost_krw_pp: 9000, ...SEONGYOJANG }),
      item("15:00", "16:30", "sight", "Seongyojang manor", "seongyojang", "An aristocratic estate of about 100 rooms kept by the same family for 10 generations, with a lotus-pond pavilion. Sweet-tier guests sleep here (check-in from 16:00) and have the grounds to themselves after the day visitors leave.", { cost_krw_pp: 5000, cost_note: "free for hanok-stay guests" }),
      item("16:45", "18:15", "night", "Coffee Festival opening evening, Anmok beach", "anmok-coffee-street", "Gangneung is Korea's coffee town: a strip of roasteries facing the sea. The festival adds tasting stalls and barista booths; go on this quiet weekday before the weekend crowds."),
      item("18:30", "19:45", "food", "Soft-tofu dinner in Chodang village", "chodang-tofu-village", "Tofu curdled with seawater, a Gangneung specialty since the 1500s; try the spicy jjamppong version at Donghwa Gaden."),
      item("20:00", "20:45", "walk", "Gyeongpo Lake at night (optional)", "gyeongpo", "A flat path around the lake past Gyeongpodae pavilion, 10 minutes from the tofu village."),
    ],
    food: [
      meal("lunch", "Jumunjin market grilled-fish set or mulhoe", "주문진 수산시장 생선구이 · 물회", null, 20000, "Mixed grilled fish with banchan, or a bowl of mulhoe to cool down.", { lat: 37.8936, lon: 128.8301 }),
      meal("snack", "Anmok beachfront roastery", "안목해변 커피거리", null, 8000, "Pick a café with a second-floor sea view; hand-drip is the local pride."),
      meal("dinner", "Donghwa Gaden (jjamppong sundubu)", "동화가든", "donghwa-gaden", 13000, "Spicy seafood soft-tofu stew; arrive before 19:00 or expect a queue."),
    ],
    rainy_swap: "Naksansa and Hajodae are fine in drizzle. In heavy rain take the Sokcho → Gangneung intercity bus (₩8,400, about 1 h) and spend the afternoon at ARTE Museum Gangneung and Anmok's cafés.",
    stay_stop: "gangneung",
  },
  {
    date: "2026-10-22", dow: "Thu", base: "Gangneung",
    title: "Odaesan: nine kilometres downhill along a mountain stream",
    summary: "A 20-minute train inland, a taxi up to Sangwonsa, then the trip's great autumn walk: Seonjae-gil follows a clear stream 9 km downhill through maples to Woljeongsa and its 1,000-year fir avenue. Mountain-greens lunch at the bottom, back to Gangneung for the night market.",
    autumn_note: "Odaesan's color peaks around Oct 16-22, so the valley should be at or just past peak, with leaves on the path. It is 5-8°C colder than the coast.",
    items: [
      item("07:45", "08:00", "transport", "Taxi to Gangneung Station", null, "Short hop from Gyeongpo.", { lat: 37.7642, lon: 128.8996 }),
      item("08:05", "08:25", "transport", "KTX-Eum Gangneung → Jinbu (Odaesan)", null, "Not every Seoul-bound train stops at Jinbu; pick one that does in Korail+.", { cost_krw_pp: 8400, booking: "Korail+ app; book the return at the same time", lat: 37.6443, lon: 128.5636 }),
      item("08:30", "09:00", "transport", "Taxi to Sangwonsa", null, "About ₩35,000 for the car up the valley road. The rural bus via Woljeongsa is cheaper but runs about hourly.", { cost_krw_pp: 11700, lat: 37.781, lon: 128.565 }),
      item("09:00", "09:40", "sight", "Sangwonsa temple", "seonjae-gil-sangwonsa", "A small mountain temple holding Korea's oldest bronze bell (725 AD)."),
      item("09:40", "13:00", "walk", "Seonjae-gil, Sangwonsa → Woljeongsa", "odaesan-seonjae-gil-woljeongsa", "A 9 km path that crosses and recrosses the stream on wooden bridges, gently downhill all the way, through the best maple color of the trip. Allow 3-3.5 h with photo stops; there are toilets and exit points along the road.", { tip: "Carry water and a snack; there are no shops on the trail." }),
      item("13:00", "13:45", "sight", "Woljeongsa and the fir-forest path", "woljeongsa-fir-forest", "The temple's octagonal nine-story pagoda, then the 1 km avenue of fir trees, some 300-plus years old, out to the Iljumun gate."),
      item("13:45", "15:00", "food", "Mountain-greens lunch by the temple", null, "Sanchae jeongsik: a table of foraged mountain vegetables, doenjang stew and grilled fish.", { lat: 37.725, lon: 128.596 }),
      item("15:30", "15:55", "transport", "Bus Woljeongsa → Jinbu", null, "Rural bus, T-money or cash; a taxi is about ₩20,000 for the car if the timing doesn't fit.", { cost_krw_pp: 2000, lat: 37.6443, lon: 128.5636 }),
      item("16:20", "16:40", "transport", "KTX-Eum Jinbu → Gangneung", null, "Back for a rest before dinner.", { cost_krw_pp: 8400, lat: 37.7642, lon: 128.8996 }),
      item("18:30", "20:30", "night", "Gangneung Jungang Market and Wolhwa Street", null, "Graze the market's fried squid, potato pancakes and dakgangjeong, then walk Wolhwa Street, a park built on the old railway line.", { lat: 37.7543, lon: 128.899 }),
    ],
    food: [
      meal("lunch", "Odaesan sanchae jeongsik", "오대산 산채정식", "odaesan-sanchae", 20000, "Temple-country food: 20-odd small dishes of mountain greens."),
      meal("dinner", "Gangneung Jungang Market grazing", "강릉중앙시장 · 월화거리", "gangneung-jungang-market", 15000, "Try the potato ongsimi (dumplings in soup) and squid sundae."),
    ],
    rainy_swap: "Seonjae-gil can close in heavy rain. Stay in Gangneung instead: Ojukheon, Terarosa's coffee factory in Gujeong, and ARTE Museum Gangneung, with the market in the evening.",
    stay_stop: "gangneung",
  },
  {
    date: "2026-10-23", dow: "Fri", base: "Seoul",
    title: "Black bamboo, silver grass, Friday night in Hongdae",
    summary: "A last Gangneung morning at Ojukheon, the black-bamboo birthplace of the scholar on the ₩5,000 note, then two hours on the KTX back to Seoul. The Seoul Eulalia Festival's final evening at Haneul Park, then Friday night in Hongdae.",
    autumn_note: "Today is 상강 (Sanggang), 'frost descent', the last solar term of autumn. Last evening of the Seoul Eulalia Festival (open to 21:00), with the silver grass at peak. Sunset about 17:47.",
    items: [
      item("09:30", "10:45", "sight", "Ojukheon", "ojukheon", "Birthplace of the scholar Yulgok (on the ₩5,000 note) and his mother Shin Saimdang (on the ₩50,000 note): a 15th-century house in a grove of black bamboo, a 15-minute walk from Seongyojang.", { cost_krw_pp: 3000 }),
      item("11:00", "11:20", "transport", "Taxi to Gangneung Station", null, "Pick up any bags left at the hotel first.", { lat: 37.7642, lon: 128.8996 }),
      item("11:30", "13:30", "transport", "KTX-Eum Gangneung → Seoul Station", null, "About 2 hours. Buy a dosirak (lunch box) at the station if you're hungry.", { cost_krw_pp: 27600, booking: "Korail+ app or korail.com; Friday trains in foliage season sell out, so book now", lat: 37.5547, lon: 126.9707 }),
      item("13:45", "14:40", "food", "Late lunch at Myeongdong Kyoja", "myeongdong", "Two stops on Line 4 from Seoul Station: garlicky kalguksu noodles and dumplings since 1966.", { lat: 37.5625, lon: 126.9856 }),
      item("15:00", "15:45", "rest", "Back to 4rest Stay", null, "Same hotel as the first stay; your suitcases are waiting.", { ...HOTEL }),
      item("16:15", "18:30", "sight", "Haneul Park silver grass at sunset", "haneul-park-silver-grass", "The festival's last evening. Line 6 to World Cup Stadium, then the 291 wooden steps (or the electric cart) up a former landfill now covered in silver grass taller than you, glowing at sunset and lit after dark.", { cost_note: "free; electric cart about ₩3,000" }),
      item("19:00", "22:30", "night", "Hongdae and Yeonnam-dong", "hongdae-yeonnam", "Friday is Hongdae's big night: buskers and dance crews on the main street, then the Gyeongui Line Forest Park in Yeonnam-dong for bars along the old rail line. Two stops from Haneul Park on Line 6, then Line 2."),
    ],
    food: [
      meal("lunch", "Myeongdong Kyoja", "명동교자", "myeongdong-kyoja", 11000, "One kalguksu each plus a shared plate of mandu; refills of noodles are free."),
      meal("dinner", "Hongdae galmaegisal BBQ", "홍대 갈매기살", null, 25000, "Pork skirt grilled at the table, a Mapo specialty; any busy grill on Hongdae's back streets.", { lat: 37.5554, lon: 126.9236 }),
      meal("drinks", "Gyeongui Line Forest Park bars", "경의선숲길 연남동", null, 20000, "Craft beer and makgeolli bars along the park.", { lat: 37.5604, lon: 126.9248 }),
    ],
    rainy_swap: "Haneul Park is exposed to wind and rain; swap it for the Starfield COEX Library or a jjimjilbang, and keep Hongdae, which is mostly indoors.",
    stay_stop: "seoul-2",
  },
  {
    date: "2026-10-24", dow: "Sat", base: "Seoul",
    title: "Hanbok at the main palace, the city wall at sunset, a sushi counter",
    summary: "Gyeongbokgung in rented hanbok (free entry) for the guard ceremony, lunch and lanes in Seochon, a short steep climb on the Inwangsan city wall for sunset over the palace, then the omakase dinner.",
    autumn_note: "Gyeongbokgung's ginkgos are starting to turn; Inwangsan's oaks show early color. Sunset about 17:46.",
    items: [
      item("09:00", "09:45", "shop", "Hanbok rental near Gyeongbokgung", "hanbok-rental", "Basic 4-hour rental with hair accessories; anyone in hanbok enters the palaces free.", { cost_krw_pp: 25000 }),
      item("09:45", "12:15", "sight", "Gyeongbokgung in hanbok", "gyeongbokgung", "Be at Gwanghwamun for the 10:00 guard-changing ceremony, then Gyeonghoeru, the banquet pavilion on its lake, and Hyangwonjeong at the back. Geunjeongjeon's courtyard is partly closed for works until Oct 31.", { cost_note: "free in hanbok (₩3,000 otherwise)" }),
      item("12:30", "13:30", "food", "Lunch in Seochon", "seochon", "Ginseng chicken soup at Tosokchon, around the corner from the palace's west gate."),
      item("13:30", "15:30", "walk", "Seochon lanes and Tongin Market", "seochon", "Return the hanbok, then wander the older, quieter neighborhood west of the palace: galleries, small cafés and Tongin Market's coin lunchbox stalls."),
      item("15:45", "18:15", "walk", "Inwangsan city-wall sunset hike", "inwangsan", "A steep 45-minute stair climb along the Joseon fortress wall to granite outcrops over Gyeongbokgung, Bugaksan and the whole city. Lit stairs for the walk down.", { tip: "Bring a headlamp or phone light and a windproof layer." }),
      item("19:00", "21:00", "food", "Omakase dinner", null, "Entry tier: Sushi Sora Gwanghwamun (about ₩110,000). Splurge: Sushi Cho at the Westin Josun (about ₩340,000). Both are short taxi rides from the hotel.", { booking: "CatchTable Global (Sushi Sora); Westin Josun site or phone (Sushi Cho). Book now.", lat: 37.565, lon: 126.98 }),
      item("21:15", "22:00", "walk", "Cheonggyecheon stream at night", "cheonggyecheon-ddp", "A walk along the lit stream back toward Jongno.", { lat: 37.569, lon: 126.978 }),
    ],
    food: [
      meal("lunch", "Tosokchon Samgyetang", "토속촌 삼계탕", "tosokchon", 21000, "A whole young chicken stuffed with rice and ginseng; long but fast-moving queue."),
      meal("dinner", "Sushi Sora Gwanghwamun (or Sushi Cho)", "스시소라 광화문 / 스시조", "sushi-sora", 110000, "Entry-tier counter omakase; Sushi Cho is the Japanese-trained high end."),
    ],
    rainy_swap: "Gyeongbokgung works under umbrellas (skip the hanbok). Swap Inwangsan for the National Museum of Korea (free, open to 21:00 on Saturdays) and keep the sushi dinner.",
    stay_stop: "seoul-2",
  },
  {
    date: "2026-10-25", dow: "Sun", base: "Seoul → ICN",
    title: "Fish-market brunch, a national treasure house, home",
    summary: "Bags to Seoul Station's luggage counter, a raw-fish brunch at Noryangjin (pick it downstairs, eat it upstairs), the free National Museum of Korea, then the AREX to Incheon with time to spare.",
    autumn_note: "Jamsu Bridge is car-free again today if you want one last river walk; Banpo is 10 minutes from the museum by taxi.",
    items: [
      item("09:30", "09:45", "transport", "Check out, taxi to Seoul Station", "seoul-station", "Leave the bags at the T-Luggage counter (09:00-22:00) or lockers for the day.", { cost_krw_pp: 3000, cost_note: "counted in local transit" }),
      item("10:15", "12:15", "food", "Noryangjin Fish Market brunch", "noryangjin", "Line 1 from Seoul Station, 10 min. Choose live fish, king crab or abalone at a stall downstairs (agree the price per kilo first), then take it to an upstairs restaurant that slices it and makes a spicy fish stew from the bones (setting fee about ₩5,000-10,000 per person)."),
      item("12:45", "15:30", "sight", "National Museum of Korea", "national-museum-of-korea", "One of the world's great museums, and free: the Room of Quiet Contemplation with two pensive Bodhisattvas, Silla gold crowns and Goryeo celadon. The 'Our Dining Table' special exhibition closes today."),
      item("15:45", "16:45", "walk", "Jamsu Bridge car-free festival (optional)", "han-river-parks", "A last look at the river, 10 minutes by taxi from the museum.", { lat: 37.5106, lon: 126.9958 }),
      item("17:00", "17:20", "transport", "Collect bags at Seoul Station", "seoul-station", "Taxi from Banpo about 20-25 min."),
      item("17:20", "18:03", "transport", "AREX Express to Incheon T1", "seoul-station", "Express every 30-40 min. Air Premia can't use Seoul Station city check-in, so take the bags with you.", { cost_krw_pp: 13000, booking: "Machines at the AREX concourse, or Klook/Trip.com vouchers (about ₩11,000)" }),
      item("21:55", null, "transport", "Air Premia departs ICN", "incheon-airport-t1", "Check-in usually opens 3 hours before departure. Spend leftover won at the T1 food court.", { lat: 37.4492, lon: 126.4508 }),
    ],
    food: [
      meal("lunch", "Noryangjin market raw fish", "노량진수산시장 활어회", "noryangjin", 35000, "Flatfish or rockfish sashimi for three plus maeuntang stew from the bones."),
      meal("dinner", "Incheon T1 food court", "인천공항 T1 푸드코트", null, 15000, "Bibimbap or tteokbokki before security.", { lat: 37.4492, lon: 126.4508 }),
    ],
    rainy_swap: "Nothing changes: Noryangjin and the museum are indoors. Skip the river.",
    stay_stop: "seoul-2",
  },
];
